name: Enforce Changelog

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  enforce-changelog:
    runs-on: ubuntu-latest

    if: >-
      !contains(github.event.pull_request.labels.*.name, 'no ci') &&
      !contains(github.event.pull_request.labels.*.name, 'no changelog') &&
      github.actor != 'dependabot[bot]'

    steps:
      - uses: brettcannon/check-for-changed-files@v1
        with:
          file-pattern: |
            .changes/unreleased/*.yaml
            CHANGELOG.md
