name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    if: >-
      (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'no ci')) ||
      github.event_name == 'push'

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: arduino/setup-task@v2
        with:
          version: 3.x

      - run: task ci-lint
